info:
  component: Mancala game

server:
  port: 8082
  forward-headers-strategy: framework

springdoc:
  packagesToScan: com.mancala.game
  api-docs:
    path: /api-docs
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game?currentSchema=game
    ssl: true
    username: postgres
    password: admin

    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
      event:
        merge:
          entity_copy_observer: allow
  sql:
    init:
      platform: POSTGRESQL